export const colorThemes = {
  dark: {
    background_color: "#07111f",
    surface_color: "#0d1b31",
    text_color: "#eaf2ff",
    primary_action_color: "#38bdf8",
    secondary_action_color: "#22c55e",
    name: "Dark",
  },
  light: {
    background_color: "#f8f9fb",
    surface_color: "#494848",
    text_color: "#1a1a2e",
    primary_action_color: "#3b82f6",
    secondary_action_color: "#10b981",
    name: "Light",
  },
  ocean: {
    background_color: "#0f172a",
    surface_color: "#1e3a5f",
    text_color: "#e0f2fe",
    primary_action_color: "#06b6d4",
    secondary_action_color: "#0284c7",
    name: "Ocean",
  },
  forest: {
    background_color: "#0d1117",
    surface_color: "#1a3a2e",
    text_color: "#d4f4dd",
    primary_action_color: "#10b981",
    secondary_action_color: "#34d399",
    name: "Forest",
  },
  sunset: {
    background_color: "#2d1810",
    surface_color: "#3f2f1f",
    text_color: "#fef3c7",
    primary_action_color: "#f97316",
    secondary_action_color: "#ec4899",
    name: "Sunset",
  },
  cyberpunk: {
    background_color: "#0a0e27",
    surface_color: "#1a0033",
    text_color: "#ff00ff",
    primary_action_color: "#ff00ff",
    secondary_action_color: "#00ffff",
    name: "Cyberpunk",
  },
};